name: CI
on:
    pull_request:
    push:
jobs:
    Test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - ubuntu-24.04-arm
                compiler:
                    - gcc-14
                    - clang-19
                    
        steps:
            - uses: actions/checkout@v4
            - uses: aminya/setup-cpp@v1
              with:
                compiler: ${{ matrix.compiler }}
                ninja: true
                meson: true
                python: true
                gcovr: true
                setup-cpp: true
            - name: show env
              run: env
            - name: setup build directory
              run: |
                mkdir -p subprojects
                meson wrap install gtest
                meson setup --buildtype release --werror build .
            - name: compile
              run: (cd build ; meson compile)
            - name: run
              run: (cd build ; ./mango)

            
